### ISSUE TITLE
CI build fails with JS import error

### ISSUE THREAD

**Issue by johanbrook** [lumeland/lume#167]
I'm running my site build-and-deploy in CI as a GitHub Action. It has worked flawlessly with lume up until today, where I got two of these errors. The weird part is that it "fixed itself" after I pushed another commit, but then it reappeared.

I haven't ever encountered this locally when building or serving with `lume`.

**[Direct link to failed run](https://github.com/johanbrook/johanbrook.com/runs/4997498931?check_suite_focus=true).**

The log:

```
Run deno run -A https://deno.land/x/lume@v1.4.3/ci.ts --location=https://johan.im --quiet
Download https://deno.land/x/lume@v1.4.3/ci.ts
Download https://deno.land/x/lume@v1.4.3/core/errors.ts
Download https://deno.land/x/lume@v1.4.3/deps/base64.ts
Download https://deno.land/x/lume@v1.4.3/deps/colors.ts
Download https://deno.land/x/lume@v1.4.3/deps/flags.ts
Download https://deno.land/x/lume@v1.4.3/deps/path.ts
Download https://deno.land/std@0.121.0/encoding/base64.ts
Download https://deno.land/std@0.121.0/path/mod.ts
Download https://deno.land/std@0.121.0/flags/mod.ts
Download https://deno.land/std@0.121.0/fmt/colors.ts
Download https://deno.land/x/lume@v1.4.3/core.ts
Download https://deno.land/std@0.121.0/_util/assert.ts
Download https://deno.land/std@0.121.0/_util/os.ts
Download https://deno.land/std@0.121.0/path/_interface.ts
Download https://deno.land/std@0.121.0/path/common.ts
Download https://deno.land/std@0.121.0/path/glob.ts
Download https://deno.land/std@0.121.0/path/posix.ts
Download https://deno.land/std@0.121.0/path/separator.ts
Download https://deno.land/std@0.121.0/path/win32.ts
Download https://deno.land/x/lume@v1.4.3/core/asset_loader.ts
Download https://deno.land/x/lume@v1.4.3/core/component_loader.ts
Download https://deno.land/x/lume@v1.4.3/core/data_loader.ts
Download https://deno.land/x/lume@v1.4.3/core/engines.ts
Download https://deno.land/x/lume@v1.4.3/core/events.ts
Download https://deno.land/x/lume@v1.4.3/core/filesystem.ts
Download https://deno.land/x/lume@v1.4.3/core/includes_loader.ts
Download https://deno.land/x/lume@v1.4.3/core/logger.ts
Download https://deno.land/x/lume@v1.4.3/core/page_loader.ts
Download https://deno.land/x/lume@v1.4.3/core/processors.ts
Download https://deno.land/x/lume@v1.4.3/core/reader.ts
Download https://deno.land/x/lume@v1.4.3/core/renderer.ts
Download https://deno.land/x/lume@v1.4.3/core/scopes.ts
Download https://deno.land/x/lume@v1.4.3/core/scripts.ts
Download https://deno.land/x/lume@v1.4.3/core/site.ts
Download https://deno.land/x/lume@v1.4.3/core/source.ts
Download https://deno.land/x/lume@v1.4.3/core/writer.ts
Download https://deno.land/std@0.121.0/path/_constants.ts
Download https://deno.land/std@0.121.0/path/_util.ts
Download https://deno.land/x/lume@v1.4.3/deps/fs.ts
Download https://deno.land/x/lume@v1.4.3/deps/fs_copy.ts
Download https://deno.land/x/lume@v1.4.3/core/utils.ts
Download https://deno.land/x/lume@v1.4.3/core/extensions.ts
Download https://deno.land/x/lume@v1.4.3/core/components.ts
Download https://deno.land/x/lume@v1.4.3/core/loaders/text.ts
Download https://deno.land/x/lume@v1.4.3/core/static_files.ts
Download https://deno.land/std@0.121.0/fs/mod.ts
Download https://deno.land/x/lume@v1.4.3/deps/dom.ts
Download https://deno.land/std@0.121.0/fs/empty_dir.ts
Download https://deno.land/std@0.121.0/fs/ensure_dir.ts
Download https://deno.land/std@0.121.0/fs/ensure_file.ts
Download https://deno.land/std@0.121.0/fs/ensure_link.ts
Download https://deno.land/std@0.121.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.121.0/fs/eol.ts
Download https://deno.land/std@0.121.0/fs/exists.ts
Download https://deno.land/std@0.121.0/fs/expand_glob.ts
Download https://deno.land/std@0.121.0/fs/move.ts
Download https://deno.land/std@0.121.0/fs/walk.ts
Download https://deno.land/x/lume@v1.4.3/core/loaders/yaml.ts
Download https://deno.land/std@0.121.0/fs/_util.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/deno-dom-wasm.ts
Download https://deno.land/x/lume@v1.4.3/deps/yaml.ts
Download https://deno.land/std@0.121.0/encoding/yaml.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/build/deno-wasm/deno-wasm.js
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/api.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/parser.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/deserialize.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/document.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/dom-parser.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/element.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/html-collection.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/node-list.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/node.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/constructor-lock.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/nwsapi-types.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/parse.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/mod.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/stringify.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/error.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/utils.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/dumper/dumper.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/dumper/dumper_state.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/core.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/default.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/extended.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/failsafe.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/schema/json.ts
Download https://deno.land/x/deno_dom@v0.1.21-alpha/src/dom/nwsapi.js
Download https://deno.land/std@0.121.0/encoding/_yaml/state.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/mod.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/mark.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/loader/loader.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/loader/loader_state.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/binary.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/bool.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/float.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/function.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/int.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/map.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/merge.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/nil.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/omap.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/pairs.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/regexp.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/seq.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/set.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/str.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/timestamp.ts
Download https://deno.land/std@0.121.0/encoding/_yaml/type/undefined.ts
Download https://deno.land/std@0.121.0/io/buffer.ts
Download https://deno.land/std@0.121.0/bytes/bytes_list.ts
Download https://deno.land/std@0.121.0/bytes/mod.ts
Download https://deno.land/std@0.121.0/io/types.d.ts
Download https://deno.land/std@0.121.0/bytes/equals.ts
Check https://deno.land/x/lume@v1.4.3/ci.ts
Loading config file /home/runner/work/johanbrook.com/johanbrook.com/_config.ts

Warning Implicitly using latest version (0.123.0) for https://deno.land/std/encoding/base64.ts

TypeError: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: https://jspm.dev/npm:@jspm/core@2/nodelibs/process
    at https://jspm.dev/browserslist@4.16.6:7:8
    at (https://jspm.dev/browserslist@4.16.6:7:8)
    at async createSite (https://deno.land/x/lume@v1.4.3/cli/utils.ts:66:17)
    at async Command.build [as fn] (https://deno.land/x/lume@v1.4.3/cli/build.ts:26:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.20.1/command/command.ts:1014:7)
    at async Command.parse (https://deno.land/x/cliffy@v0.20.1/command/command.ts:928:16)
    at async (https://deno.land/x/lume@v1.4.3/cli.ts:152:5)
Error: Process completed with exit code 1.
```

Let me know if this seems like it's something in my own code.

**Comment by oscarotero** [comment]
It looks like a temporary error in jspm.dev CDN. I just built it in local and seems to work fine. Try to re-run the build again.

**Comment by johanbrook** [comment]
Yep, seems like it. Thanks for checking and for your time!
