### ISSUE TITLE
How to write client side (javascript) code ?

### ISSUE THREAD

**Issue by max-l** [lumeland/lume#396]
### Enter your suggestions in details:

From reading about components in the doc: https://lume.land/docs/core/components/

it appears that writting client side javascript is done with components.

I wrote a component in ./_components/MyComponent.jsx  (as suggested by the doc),

and it works fine as a component, i.e. it gets rendered correctly.

However, if I add a client side handler, it doesn't get fired : 

```
<button onClick={() => {
      console.log("!!!")
  }}>MyButton...</button>
```

I figured I have to tell Lume that the component uses client side react.

I tried adding this import the header : 
`
import React from "react";
`
Hopping that Lume would "discover" the use of client side react.

It did not help, client side click handler doesn't work.

Perhaps there is a config to let Lume know of the react client side dependency ?

I also added this to deno.json : 

```
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.15.3/",
    "react/jsx-runtime": "https://esm.sh/react@18.2.0/jsx-runtime",
    "react":  "https://esm.sh/react@18.2.0"
  }

```

I also tried tu make use of useEffect:

``` 
import React,{useEffect} from "react";

export default ({}) => {
    useEffect(() => {
        console.log(res)
    },[])    
  return <button onClick={() => {
      console.log("!!!")
  }}>MyButton...</button>
}

```

And something is definitely wrong with my setup, because I get this:

```
Error: Error rendering the layout of this page
- page: /index.jsx
    at (https://deno.land/x/lume@v1.15.3/core/renderer.ts:162:19)

Caused by TypeError: Cannot read properties of null (reading 'useEffect')
    at n.useEffect (https://esm.sh/stable/react@18.2.0/deno/react.js:2:6284)
    at default (file:///home/maxou/dev/site-altorf/altorf/python-lib/openprot_pipeline/site/_components/button.jsx:6:5)
    | 6 |     useEffect(() => {
    | ~ | ~~~~^
    | 7 |         console.log("...")

    at JsxEngine.renderSync (https://deno.land/x/lume@v1.15.3/plugins/jsx.ts:76:9)
    at (https://deno.land/x/lume@v1.15.3/core/component_loader.ts:111:39)
    at Object.render (https://deno.land/x/lume@v1.15.3/core/component_loader.ts:110:32)
    at (https://deno.land/x/lume@v1.15.3/core/source.ts:542:60)
    at renderWithHooks (file:///home/maxou/.cache/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5661:16)

```

**Comment by oscarotero** [comment]
Lume components are rendered in building time, they are not intended for client side. You can include client-side CSS and JS code in the components but using the `css` and `js` named exports. For example:

```ts
// CSS code
export const css = `
button {
  background-color: blue;
}
`;

// Client side JavaScript code
export const js = `
function clickButton() {
    alert("You've clicked me!");
}
`;

// Component to render on building:
export default function () {
  return <button onclick="clickButton()">Click me</button>
}
```

This can be useful for web components or simple use cases.
If you need to ship more client side javascript, you can use the [esbuild plugin](https://lume.land/plugins/esbuild/) that can compile JS(X) and TS(X).

Take a look to the [react-todo demo](https://github.com/lumeland/react-todo) for a more advanced example, it's a web application built with React, pre-rendered in building time and hydrated in client side.

**Comment by max-l** [comment]
Thanks for the quick response, it works !
