### ISSUE TITLE
MDX plugin fails to render

### ISSUE THREAD

**Issue by nubunto** [lumeland/lume#414]
### Version

1.16.2

### Platform

MacOS 13.3.1

### What steps will reproduce the bug?

1. Clone the repository https://github.com/nubunto/lume_test
2. run `deno task serve`

### How often does it reproduce? Is there a required condition?

follow the above steps and it should reproduce every time.

### What is the expected behavior?

Site should build correctly, with two pages: `/` and `/emedexis`

### What do you see instead?

```
Error: Error rendering this page
- page: /emedexis.mdx
    at (https://deno.land/x/lume@v1.16.2/core/renderer.ts:138:19)
    at async concurrent (https://deno.land/x/lume@v1.16.2/core/utils.ts:181:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v1.16.2/core/renderer.ts:126:7)
    at async Site.#buildPages (https://deno.land/x/lume@v1.16.2/core/site.ts:598:5)
    at async Site.build (https://deno.land/x/lume@v1.16.2/core/site.ts:526:9)
    at async build (https://deno.land/x/lume@v1.16.2/cli/build.ts:36:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.16.2/cli.ts:158:3)

Caused by ReferenceError: React is not defined
    at _createMdxContent (data:text/jsx;base64,CmV4cG9ydCBkZWZhdWx0......dGVudAp9OwoKfQogICAg:9:3)
    at MDXContent (data:text/jsx;base64,CmV4cG9ydCBkZWZhdWx0......dGVudAp9OwoKfQogICAg:13:91)
    at MDXEngine.render (https://deno.land/x/lume@v1.16.2/plugins/mdx.ts:83:18)
    at async Renderer.render (https://deno.land/x/lume@v1.16.2/core/renderer.ts:200:19)
    at async Renderer.#renderPage (https://deno.land/x/lume@v1.16.2/core/renderer.ts:226:12)
    at async (https://deno.land/x/lume@v1.16.2/core/renderer.ts:135:34)
    at async concurrent (https://deno.land/x/lume@v1.16.2/core/utils.ts:181:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v1.16.2/core/renderer.ts:126:7)
    at async Site.#buildPages (https://deno.land/x/lume@v1.16.2/core/site.ts:598:5)
```

**Comment by oscarotero** [comment]
This is because Deno use React by default to render JSX. You have to [configure Deno to use preact](https://lume.land/plugins/jsx_preact/#configuration). Add the following to your `deno.json` file:

```json
"compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "npm:preact"
  }
```

**Comment by oscarotero** [comment]
Sure, It would be great. Thanks!
