### ISSUE TITLE
The `svgo` dependancy (for the `svg` plugin) is causing `lume` to fail

### ISSUE THREAD

**Issue by peterlobster** [lumeland/lume#43]
`lume` isn't working today for some reason. It seems the `svgo` dependency is to blame. 

This is what happens when I try to use `lume`...

```shell
$ lume
Download https://jspm.dev/svgo/plugins/convertEllipseToCircle.js
Download https://jspm.dev/svgo/plugins/removeUnknownsAndDefaults.js
Download https://jspm.dev/svgo/plugins/collapseGroups.js
Download https://jspm.dev/svgo/plugins/convertShapeToPath.js
Download https://jspm.dev/svgo/plugins/convertColors.js
Download https://jspm.dev/svgo/plugins/removeEmptyText.js
Download https://jspm.dev/svgo/plugins/cleanupAttrs.js
Download https://jspm.dev/svgo/plugins/removeDesc.js
Download https://jspm.dev/svgo/plugins/cleanupNumericValues.js
Download https://jspm.dev/svgo/plugins/removeMetadata.js
Download https://jspm.dev/svgo/plugins/minifyStyles.js
Download https://jspm.dev/svgo/plugins/removeHiddenElems.js
Download https://jspm.dev/svgo/plugins/removeUselessDefs.js
Download https://jspm.dev/svgo/plugins/mergePaths.js
Download https://jspm.dev/svgo/plugins/inlineStyles.js
Download https://jspm.dev/svgo/plugins/cleanupEnableBackground.js
Download https://jspm.dev/svgo/plugins/removeUnusedNS.js
Download https://jspm.dev/svgo/plugins/removeXMLProcInst.js
Download https://jspm.dev/svgo/plugins/removeTitle.js
Download https://jspm.dev/svgo/plugins/removeEmptyContainers.js
Download https://jspm.dev/svgo/plugins/removeUselessStrokeAndFill.js
Download https://jspm.dev/svgo/plugins/removeEditorsNSData.js
Download https://jspm.dev/svgo/plugins/removeEmptyAttrs.js
Download https://jspm.dev/svgo/plugins/removeViewBox.js
Download https://jspm.dev/svgo/plugins/removeNonInheritableGroupAttrs.js
Download https://jspm.dev/svgo/plugins/moveGroupAttrsToElems.js
Download https://jspm.dev/svgo/plugins/sortAttrs.js
Download https://jspm.dev/svgo/plugins/sortDefsChildren.js
Download https://jspm.dev/svgo/plugins/removeDoctype.js
Download https://jspm.dev/svgo/plugins/cleanupIDs.js
Download https://jspm.dev/svgo/plugins/moveElemsAttrsToGroup.js
Download https://jspm.dev/npm:css-tree@1/dist/csstree.min.js!cjs
lume: Import 'https://jspm.dev/svgo/plugins/convertEllipseToCircle.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:34:0
TypeError: Import 'https://jspm.dev/svgo/plugins/convertEllipseToCircle.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:34:0
    at async buildSite (https://deno.land/x/lume@v0.16.1/cli/utils.js:15:19)
    at async Module.run (https://deno.land/x/lume@v0.16.1/cli/build.js:44:16)
    at async maybeRun (https://deno.land/x/lume@v0.16.1/cli.js:109:28)
    at async cli (https://deno.land/x/lume@v0.16.1/cli.js:117:5)
    at async https://deno.land/x/lume@v0.16.1/cli.js:56:5
```

```shell
$ lume
Download https://jspm.dev/svgo/plugins/convertColors.js
Download https://jspm.dev/svgo/plugins/removeNonInheritableGroupAttrs.js
Download https://jspm.dev/svgo/plugins/removeViewBox.js
Download https://jspm.dev/svgo/plugins/removeUnusedNS.js
Download https://jspm.dev/svgo/plugins/cleanupNumericValues.js
Download https://jspm.dev/svgo/plugins/collapseGroups.js
Download https://jspm.dev/svgo/plugins/removeTitle.js
Download https://jspm.dev/svgo/plugins/removeMetadata.js
Download https://jspm.dev/svgo/plugins/cleanupIDs.js
Download https://jspm.dev/svgo/plugins/mergePaths.js
Download https://jspm.dev/svgo/plugins/removeDesc.js
Download https://jspm.dev/svgo/plugins/removeHiddenElems.js
Download https://jspm.dev/svgo/plugins/cleanupAttrs.js
Download https://jspm.dev/svgo/plugins/removeDoctype.js
Download https://jspm.dev/svgo/plugins/convertEllipseToCircle.js
Download https://jspm.dev/svgo/plugins/removeEditorsNSData.js
Download https://jspm.dev/svgo/plugins/sortDefsChildren.js
Download https://jspm.dev/svgo/plugins/removeUnknownsAndDefaults.js
Download https://jspm.dev/svgo/plugins/convertShapeToPath.js
Download https://jspm.dev/svgo/plugins/removeEmptyAttrs.js
Download https://jspm.dev/svgo/plugins/removeEmptyContainers.js
Download https://jspm.dev/svgo/plugins/minifyStyles.js
Download https://jspm.dev/svgo/plugins/removeXMLProcInst.js
Download https://jspm.dev/svgo/plugins/inlineStyles.js
Download https://jspm.dev/svgo/plugins/sortAttrs.js
Download https://jspm.dev/svgo/plugins/removeUselessStrokeAndFill.js
Download https://jspm.dev/svgo/plugins/moveElemsAttrsToGroup.js
Download https://jspm.dev/svgo/plugins/moveGroupAttrsToElems.js
Download https://jspm.dev/svgo/plugins/cleanupEnableBackground.js
Download https://jspm.dev/svgo/plugins/removeUselessDefs.js
Download https://jspm.dev/svgo/plugins/removeEmptyText.js
Download https://jspm.dev/npm:css-tree@1/dist/csstree.min.js!cjs
lume: Import 'https://jspm.dev/svgo/plugins/convertColors.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:20:0
TypeError: Import 'https://jspm.dev/svgo/plugins/convertColors.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:20:0
    at async buildSite (https://deno.land/x/lume@v0.16.1/cli/utils.js:15:19)
    at async Module.run (https://deno.land/x/lume@v0.16.1/cli/build.js:44:16)
    at async maybeRun (https://deno.land/x/lume@v0.16.1/cli.js:109:28)
    at async cli (https://deno.land/x/lume@v0.16.1/cli.js:117:5)
    at async https://deno.land/x/lume@v0.16.1/cli.js:56:5
```

```shell
$ lume
Download https://jspm.dev/svgo/plugins/moveElemsAttrsToGroup.js
Download https://jspm.dev/svgo/plugins/convertEllipseToCircle.js
Download https://jspm.dev/svgo/plugins/cleanupEnableBackground.js
Download https://jspm.dev/svgo/plugins/removeEmptyText.js
Download https://jspm.dev/svgo/plugins/inlineStyles.js
Download https://jspm.dev/svgo/plugins/removeXMLProcInst.js
Download https://jspm.dev/svgo/plugins/removeUselessDefs.js
Download https://jspm.dev/svgo/plugins/removeEmptyContainers.js
Download https://jspm.dev/svgo/plugins/minifyStyles.js
Download https://jspm.dev/svgo/plugins/convertColors.js
Download https://jspm.dev/svgo/plugins/removeMetadata.js
Download https://jspm.dev/svgo/plugins/collapseGroups.js
Download https://jspm.dev/svgo/plugins/mergePaths.js
Download https://jspm.dev/svgo/plugins/removeEditorsNSData.js
Download https://jspm.dev/svgo/plugins/cleanupAttrs.js
Download https://jspm.dev/svgo/plugins/convertShapeToPath.js
Download https://jspm.dev/svgo/plugins/removeTitle.js
Download https://jspm.dev/svgo/plugins/sortDefsChildren.js
Download https://jspm.dev/svgo/plugins/cleanupNumericValues.js
Download https://jspm.dev/svgo/plugins/removeEmptyAttrs.js
Download https://jspm.dev/svgo/plugins/removeViewBox.js
Download https://jspm.dev/svgo/plugins/removeNonInheritableGroupAttrs.js
Download https://jspm.dev/svgo/plugins/removeUnusedNS.js
Download https://jspm.dev/svgo/plugins/cleanupIDs.js
Download https://jspm.dev/svgo/plugins/removeHiddenElems.js
Download https://jspm.dev/svgo/plugins/removeUnknownsAndDefaults.js
Download https://jspm.dev/svgo/plugins/removeUselessStrokeAndFill.js
Download https://jspm.dev/svgo/plugins/removeDoctype.js
Download https://jspm.dev/svgo/plugins/removeDesc.js
Download https://jspm.dev/svgo/plugins/sortAttrs.js
Download https://jspm.dev/svgo/plugins/moveGroupAttrsToElems.js
Download https://jspm.dev/npm:css-tree@1/dist/csstree.min.js!cjs
lume: Import 'https://jspm.dev/svgo/plugins/moveElemsAttrsToGroup.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:29:0
TypeError: Import 'https://jspm.dev/svgo/plugins/moveElemsAttrsToGroup.js' failed: 404 Not Found
    at https://deno.land/x/lume@v0.16.1/deps/svgo.js:29:0
    at async buildSite (https://deno.land/x/lume@v0.16.1/cli/utils.js:15:19)
    at async Module.run (https://deno.land/x/lume@v0.16.1/cli/build.js:44:16)
    at async maybeRun (https://deno.land/x/lume@v0.16.1/cli.js:109:28)
    at async cli (https://deno.land/x/lume@v0.16.1/cli.js:117:5)
    at async https://deno.land/x/lume@v0.16.1/cli.js:56:5
```

**Comment by oscarotero** [comment]
Hi. thanks for reporting this. I'm on it.

**Comment by peterlobster** [comment]
@oscarotero Thanks @oscarotero. The simple way to fix this temporarily is to disable the `svg` plugin.

**Comment by oscarotero** [comment]
What do you mean? `svg` plugin is disabled by default.

**Comment by peterlobster** [comment]
I added it, that's why.

**Comment by oscarotero** [comment]
I've released https://github.com/lumeland/lume/releases/tag/v0.16.3 that fixes this issue.
SVG plugin is working again.
