### ISSUE TITLE
Allow Lume to run offline

### ISSUE THREAD

**Issue by cvburgess** [lumeland/lume#496]
### Enter your suggestions in details:

When trying to run `deno task lume --serve` lume dies with the following error:

```
TypeError: error sending request for url (https://cdn.deno.land/lume/meta/versions.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:501:7)
    at async getLatestVersion (https://deno.land/x/lume@v1.19.1/core/utils.ts:114:20)
    at async checkUpgrade (https://deno.land/x/lume@v1.19.1/core/utils.ts:97:7)
    at async build (https://deno.land/x/lume@v1.19.1/cli/build.ts:57:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.19.1/cli.ts:135:3)
```

Fetching this JSON file should fail gracefully - especially for re-builds - so devs can work from planes or trains with no issue!

**Comment by oscarotero** [comment]
Good point.
This request is done once per day, just to make sure you're using the latest version of Lume. Then it's saved in the localstorage so you can run Lume offline without problems.
But I'm agree that it shouldn't fail on offline environment. I'll add a try/catch in the next version.
