### ISSUE TITLE
The method pages of search plugin is undefined 

### ISSUE THREAD

**Issue by rafaelschueng** [lumeland/lume#500]
### Version

1.18.0

### Platform

Windows

### What steps will reproduce the bug?

I created a JSX component that fetches all trending posts in my blog and renders a list. But the problem starts when I try access the method `pages` in `Search ` helper class my JSX component. I receive the following error:

```powershell
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "--serve"
Loading config file file:///C:/Users/rafae/Projects/Personal_Blog_New/_config.ts

Error: Error rendering the layout of this page
- page: /index.mdx
    at (https://deno.land/x/lume@v1.18.0/core/renderer.ts:157:19)
    at async concurrent (https://deno.land/x/lume@v1.18.0/core/utils.ts:163:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v1.18.0/core/renderer.ts:139:7)
    at async Site.#buildPages (https://deno.land/x/lume@v1.18.0/core/site.ts:615:5)        
Caused by TypeError: Cannot read properties of undefined (reading 'pages')
    at async Site.build (https://deno.land/x/lume@v1.18.0/core/site.ts:530:9)
    at async build (https://deno.land/x/lume@v1.18.0/cli/build.ts:41:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.18.0/cli.ts:134:3)

    at TredingBlogPosts (file:///C:/Users/rafae/Projects/Personal_Blog_New/src/_components/home/TrendingBlogPosts.tsx:5:26)
    | 4 | const TredingBlogPosts = ({ search }: PageData) => {
    | 5 |     const posts = search.pages('blog');
    | ~ | ~~~~~~~~~~~~~~~~~~~~~~~~~^
    | 6 |     if (!posts.length) return (<> No new posts </>)
``` 

I don't know why is not working. 

### What do you see instead?

```powershell
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "--serve"
Loading config file file:///C:/Users/rafae/Projects/Personal_Blog_New/_config.ts

Error: Error rendering the layout of this page
- page: /index.mdx
    at (https://deno.land/x/lume@v1.18.0/core/renderer.ts:157:19)
    at async concurrent (https://deno.land/x/lume@v1.18.0/core/utils.ts:163:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v1.18.0/core/renderer.ts:139:7)
    at async Site.#buildPages (https://deno.land/x/lume@v1.18.0/core/site.ts:615:5)        
Caused by TypeError: Cannot read properties of undefined (reading 'pages')
    at async Site.build (https://deno.land/x/lume@v1.18.0/core/site.ts:530:9)
    at async build (https://deno.land/x/lume@v1.18.0/cli/build.ts:41:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.18.0/cli.ts:134:3)

    at TredingBlogPosts (file:///C:/Users/rafae/Projects/Personal_Blog_New/src/_components/home/TrendingBlogPosts.tsx:5:26)
    | 4 | const TredingBlogPosts = ({ search }: PageData) => {
    | 5 |     const posts = search.pages('blog');
    | ~ | ~~~~~~~~~~~~~~~~~~~~~~~~~^
    | 6 |     if (!posts.length) return (<> No new posts </>)

    at renderWithHooks (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5661:16)
    at renderIndeterminateComponent (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5734:15)
    at renderElement (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:6079:14)
    at renderNode (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:6262:12)
    at renderHostElement (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5645:3)
    at renderElement (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:5955:5)
    at renderNodeDestructiveImpl (file:///C:/Users/rafae/AppData/Local/deno/npm/registry.npmjs.org/react-dom/18.2.0/cjs/react-dom-server-legacy.browser.development.js:6107:11)
```

**Comment by oscarotero** [comment]
Hi @rafaelschueng 
I just test it and works fine (version 1.18 and 1.19). How can I reproduce this error?

**Comment by rafaelschueng** [comment]
I just create a new JSX component 

```typescript
// my TrendingBlogPost.tsx file

import type { } from "react/types";
import type { PageData } from 'lume/core.ts'

const TredingBlogPosts = ({ search }: PageData) => {
    const posts = search.pages('blog');
    if (!posts.length) return (<> No new posts </>)
    return (
        <ul>
            {posts?.map((post:any) => <li>{post.data}</li>)}
        </ul>
    )
}

export default TredingBlogPosts;
``` 

When I call the component in my HomeBody.tsx(Is my component that renders my Index.tsx) and he doesn't render. The Server helper class dont have the pages method available. I don't know if I'm doing something wrong.

**Comment by oscarotero** [comment]
It works fine to me. Do you have a public repo to take a look?

Or just try this and let me know if it works fine to you:
[search-in-jsx.zip](https://github.com/lumeland/lume/files/13052373/search-in-jsx.zip)

**Comment by rafaelschueng** [comment]
> It works fine to me. Do you have a public repo to take a look?
> 
> Or just try this and let me know if it works fine to you: [search-in-jsx.zip](https://github.com/lumeland/lume/files/13052373/search-in-jsx.zip)

Here is the repository: https://github.com/rafaelschueng/Personal_Blog_New/blob/development/src/_components/home/TrendingBlogPosts.tsx

I tested your code and I don't understand why my code is not working. 

Thanks for helping me

**Comment by oscarotero** [comment]
Okay, I found the problem. You're importing the components as regular modules:

```ts
import TrendingBlogPosts from "./TrendingBlogPosts.tsx";

export default function () {
  return (
    <TrendingBlogPosts />
  )
}
```

In Lume, components are in the `comp` variable:


```ts
export default function ({ comp }) {
  return (
    <comp.home.TrendingBlogPosts />
  )
}
```

This has two advantages:

- Lume can inject automatically the common variables like `search`, `paginate`, etc.
- Live-reload works. The module system of Deno caches all modules loaded with `import ...` and it's not possible to refresh a module if the code has changed (you have to restart the server). The Lume way to load components solves that problem.

**Comment by rafaelschueng** [comment]
I forgot the fact that I'm not working with reactjs and regular components. I rewrite all my components and now works perfectly. 

Thanks for helping me. I love this SSG.
