### ISSUE TITLE
Can't run Lume

### ISSUE THREAD

**Issue by emilkrebs** [lumeland/lume#510]
### Version

v1.19.3

### Platform

Windows 11 64bit

### What steps will reproduce the bug?

Run the following in the terminal:
```
deno run -A https://deno.land/x/lume/cli.ts
```

### How often does it reproduce? Is there a required condition?

Every time

### What do you see instead?

```
YAMLError: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: {{ .Date }}
        ^
    at generateError (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:161:10)
    at throwError (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:174:9)
    at readBlockMapping (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:1191:16)
    at composeNode (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:1512:13)
    at readDocument (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:1698:3)
    at loadDocuments (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:1758:5)
    at load (https://deno.land/std@0.204.0/yaml/_loader/loader.ts:1788:21)
    at parse (https://deno.land/std@0.204.0/yaml/parse.ts:19:10)
    at _extract (https://deno.land/std@0.204.0/front_matter/create_extractor.ts:32:17)
    at extract (https://deno.land/std@0.204.0/front_matter/create_extractor.ts:133:12)

```

### Additional information

I think It's a problem that just happened to me...

**Comment by oscarotero** [comment]
You have an error in one of your YAML files, containing this `date: {{ .Date }}`
Probably you're migrating from Hugo and this code is not valid in Lume.

**Comment by emilkrebs** [comment]
I am just running the command in the terminal to create a new Lume project.

**Comment by emilkrebs** [comment]
Just found out I have to use
```
deno run -Ar https://deno.land/x/lume/init.ts
```
