### ISSUE TITLE
"vto is not defined"

### ISSUE THREAD

**Issue by doga** [lumeland/lume#546]
### Version

v2.0.2

### Platform

deno 1.39.1 (release, x86_64-apple-darwin), macOS 12.7.2

### What steps will reproduce the bug?

I am trying to use the [`vto()` Vento filter](https://lume.land/plugins/vento/#vto-filter), but it seems this filter is no longer available since Vento became the default templating system ?!

### Steps to reproduce

Use the `vto` filter in a Vento template:

```html
<ul>
  {{ for feature of text.plans[plan.id].features }}
    <li>
      {{ feature | vto(it) }}
    </li>
  {{ /for }}
</ul>
```

... then watch the build fail:

```sh
➜  qworum.net git:(master) ✗ deno task serve
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-s"
Loading config file file:///Users/da/home/work/ArmangilSoftware2/code/qworum/web/qworum.net/_config.ts
Error: Error rendering the layout of the page /en/plans.yaml
    at https://deno.land/x/lume@v2.0.2/core/renderer.ts:176:19
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Promise.all (index 4)
    at async concurrent (https://deno.land/x/lume@v2.0.2/core/utils/concurrent.ts:21:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v2.0.2/core/renderer.ts:155:7)
    at async Site.#buildPages (https://deno.land/x/lume@v2.0.2/core/site.ts:584:5)
    at async Site.build (https://deno.land/x/lume@v2.0.2/core/site.ts:506:9)
    at async build (https://deno.land/x/lume@v2.0.2/cli/build.ts:34:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
Caused by Error: Error in the template /_includes/layouts/plans.vto:40:9

{{ feature | vto(it) }}

> vto is not defined

    at Environment.createError (https://deno.land/x/vento@v0.10.0/src/environment.ts:277:12)
    at eval (eval at compile (https://deno.land/x/vento@v0.10.0/src/environment.ts:42:25), <anonymous>:82:23)
    at Environment.runString (https://deno.land/x/vento@v0.10.0/src/environment.ts:87:20)
    at VentoEngine.render (https://deno.land/x/lume@v2.0.2/plugins/vento.ts:93:38)
    at Renderer.render (https://deno.land/x/lume@v2.0.2/core/renderer.ts:215:32)
    at Renderer.#renderLayout (https://deno.land/x/lume@v2.0.2/core/renderer.ts:292:28)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/lume@v2.0.2/core/renderer.ts:159:28
    at async Promise.all (index 4)
    at async concurrent (https://deno.land/x/lume@v2.0.2/core/utils/concurrent.ts:21:3)
Caused by ReferenceError: vto is not defined
    at eval (eval at compile (https://deno.land/x/vento@v0.10.0/src/environment.ts:42:25), <anonymous>:56:23)
    at Environment.runString (https://deno.land/x/vento@v0.10.0/src/environment.ts:87:20)
    at VentoEngine.render (https://deno.land/x/lume@v2.0.2/plugins/vento.ts:93:38)
    at Renderer.render (https://deno.land/x/lume@v2.0.2/core/renderer.ts:215:32)
    at Renderer.#renderLayout (https://deno.land/x/lume@v2.0.2/core/renderer.ts:292:28)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/lume@v2.0.2/core/renderer.ts:159:28
    at async Promise.all (index 4)
    at async concurrent (https://deno.land/x/lume@v2.0.2/core/utils/concurrent.ts:21:3)
    at async Renderer.renderPages (https://deno.land/x/lume@v2.0.2/core/renderer.ts:155:7)
```

### How often does it reproduce? Is there a required condition?

This happens every time I try to use the `vto()` filter.

### What is the expected behavior?

The build is expected to succeed.

### What do you see instead?

The build aborts.

### Additional information

__Is there an additional step__ to take for activating the `vto()` filter since Vento became Lume's default templating system?

**Comment by oscarotero** [comment]
Vento filters use the pipe operator `|>`. This should work:

```
{{ feature |> vto(it) }}
```

The example in the documentation is from Nunjucks (maybe it's confusing, I'll fix it).

**Comment by doga** [comment]
`{{ feature |> vto(it) }}` does not fix it. I get `[object Promise]` displayed, regardless of whether the piped text contains markup to replace or not:

<img width="214" alt="Screenshot 2024-01-04 at 00 35 38" src="https://github.com/lumeland/lume/assets/212690/20e17f52-1f69-45d5-83c1-46dfcc2df158">

**Comment by oscarotero** [comment]
I see. `vto` filter is async. You have to do `{{ feature |> await vto(it) }}`.

**Comment by doga** [comment]
That fixed it, thanks.

_Sidenote:_ Vento's `vto` filter is extremely useful for i18n'ed websites, and since Vento is now officially part of Lume, I am officially retiring my [lume_cross_language_content Lume plugin](https://deno.land/x/lume_cross_language_content@v2.0.1), which was serving the same purpose. `lume_cross_language_content` wasn't really compatible with `deno task serve`, although it was working perfectly with `deno task build`.
