### ISSUE TITLE
Transform Images plugin: "VipsOperation: class "jxlsave_buffer" not found"

### ISSUE THREAD

**Issue by johanbrook** [lumeland/lume#630]
### Version

2.2.2

### Platform

macOS Sonoma 14.4

### What steps will reproduce the bug?

**_config.ts**

```ts
import lume from "lume/mod.ts";
import picture from "lume/plugins/picture.ts";
import transform_images from "lume/plugins/transform_images.ts";

const site = lume();

site.use(picture());
site.use(transform_images());

export default site;
```

**index.page.ts**

```ts
export default function () {
    return `
        <html>
            <body>
                <div transform-images="jxl avif jpg 647@2">
                    <img src="/uploads/img_2158.jpg" alt="">
                </div>
            </body>
        </html>
    `;
}
```

Then run:

```
deno task serve
```

### How often does it reproduce? Is there a required condition?

Every time.

### What is the expected behavior?

The correct images are generated into `_site/uploads`.

### What do you see instead?

```
Loading config file file:///Users/brookie/code/travelling-brooks/_config.ts
Error: VipsOperation: class "jxlsave_buffer" not found
    at Sharp.toBuffer (file:///Users/brookie/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.33.4/lib/output.js:161:17)
    at transform (https://deno.land/x/lume@v2.2.1/plugins/transform_images.ts:203:45)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async processPage (https://deno.land/x/lume@v2.2.1/plugins/transform_images.ts:143:13)
    at async Promise.all (index 0)
    at async concurrent (https://deno.land/x/lume@v2.2.1/core/utils/concurrent.ts:21:3)
    at async process (https://deno.land/x/lume@v2.2.1/plugins/transform_images.ts:101:7)
    at async Processors.run (https://deno.land/x/lume@v2.2.1/core/processors.ts:32:7)
    at async Site.#buildPages (https://deno.land/x/lume@v2.2.1/core/site.ts:687:5)
    at async Site.build (https://deno.land/x/lume@v2.2.1/core/site.ts:530:9) {
  message: 'VipsOperation: class "jxlsave_buffer" not found'
}
```

### Additional information

Removing `jxl` from `transform-images="jxl avif jpg 647@2"` fixes it.

**Comment by oscarotero** [comment]
It seems a bug in sharp library. I've created this issue: https://github.com/lovell/sharp/issues/4153

**Comment by oscarotero** [comment]
I got response. Seems that it requires to compile libvips with support for libjxl. It will change when [jpegxl gets a bigger adoption](https://caniuse.com/jpegxl)

**Comment by oscarotero** [comment]
Probably, Lume shouldn't allow this value meanwhile.

**Comment by johanbrook** [comment]
Yep, looks like it. Good to know!

I’ll leave this issue open until you feel mentions about JPEG XL are removed from code and docs.

**Comment by oscarotero** [comment]
I'm closing this because I just released a new version of Lume without the JXL format, and it's now mentioned in the docs.
