### ISSUE TITLE
Feeds plugin: item.updated?.toISOString is not a function

### ISSUE THREAD

**Issue by basus** [lumeland/lume#638]
### Version

2.2.3

### Platform

macOS Sonoma 14.5, Deno 1.45.2

### What steps will reproduce the bug?

I'm using the feeds plugin to create a RSS feed where I set the `updated` in `items` as `=modified`. The `items` key looks like:

```
items: {
        title: "=title",
        description: "=description",
        published: "=date",
        updated: "=modified",
        image: "=cover"
    }
```

I have a number of Markdown files, some that have a `modified` front matter field, some that don't. The ones that do have them in ISO format like `modified: "2022-05-24T17:00:00"`.

### What do you see instead?

I get the following error when running `lume` or `lume --serve`:

```
TypeError: item.updated?.toISOString is not a function                                      
    at https://deno.land/x/lume@v2.2.3/plugins/feed.ts:248:43                                
    at Array.map (<anonymous>)                                                               
    at generateRss (https://deno.land/x/lume@v2.2.3/plugins/feed.ts:237:26)                  
    at https://deno.land/x/lume@v2.2.3/plugins/feed.ts:188:53                                
    at Events.dispatchEvent (https://deno.land/x/lume@v2.2.3/core/events.ts:46:19)           
    at Site.dispatchEvent (https://deno.land/x/lume@v2.2.3/core/site.ts:274:24)              
    at Site.#buildPages (https://deno.land/x/lume@v2.2.3/core/site.ts:700:23)                
    at eventLoopTick (ext:core/01_core.js:168:7)                                             
    at async Site.build (https://deno.land/x/lume@v2.2.3/core/site.ts:532:9)                 
    at async build (https://deno.land/x/lume@v2.2.3/cli/build.ts:22:3)
```

### Additional information

Removing the updated key makes everything work fine, of course with no `updated` field in the RSS.

**Comment by oscarotero** [comment]
Yes, this is a bug. The value expects a `Date` instance, but it's getting a `string`.

**Comment by oscarotero** [comment]
Hi, I just fixed this bug and will be available in the next Lume version.
For now, you can upgrade Lume to the latest development version with `deno task lume upgrade --dev`.
Feel free to reopen this if it doesn't work.
Thanks!
