### ISSUE TITLE
error: Uncaught (in worker "") (in promise) TypeError: Module not found "https://deno.land/x/lume@v2.3.2".

### ISSUE THREAD

**Issue by ooker777** [lumeland/lume#665]
I have this `_config.ts`:
```js
import lume from "https://deno.land/x/lume@v2.3.2";
const site = lume()
export default site;
```
The error:
```
deno task serve
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run -A - "-s"
Loading config file file:///D:/Programming/Test/_config.ts
Warning Implicitly using latest version (v2.3.2) for https://deno.land/x/lume
error: Uncaught (in worker "") (in promise) TypeError: Module not found "https://deno.land/x/lume@v2.3.2".
    at file:///D:/Programming/Test/_config.ts:1:18
    const mod = await import(url);
                ^
    at async createSite (https://deno.land/x/lume@v2.3.2/cli/utils.ts:26:17)
    at async buildSite (https://deno.land/x/lume@v2.3.2/cli/utils.ts:45:16)
    at async onmessage (https://deno.land/x/lume@v2.3.2/cli/build_worker.ts:23:16)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:168:7)  
```
Do you have any idea?

**Comment by oscarotero** [comment]
The module url is not correct. It must include the file name:
```js
import lume from "https://deno.land/x/lume@v2.3.2/mod.ts";
```

**Comment by ooker777** [comment]
🫣🫣🫣
